### ISSUE TITLE
期望开放编辑器大小的参数设置（宽高）

### ISSUE THREAD

**Issue by ghost** [textbus/textbus#19]

**Comment by tbhuabi** [comment]
现在可以通过 css 直接设置，无需增加设置宽高的接口哦

```css
.textbus-container { width: 800px; height: 600px; }
```
